# Generated by Django 5.0.2 on 2024-04-02 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(default=18, help_text='This field is important for our site.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='BookieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('profile_picture', models.ImageField(default='no_profile.png', upload_to='profile_pictures')),
                ('bio', models.TextField(help_text='Share something about yourself.')),
                ('bookie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('have_read', models.ManyToManyField(blank=True, default=None, related_name='have_read', to='book.book')),
                ('want_to_read', models.ManyToManyField(blank=True, default=None, related_name='want_to_read', to='book.book')),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
