# Generated by Django 5.0.2 on 2024-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('bookie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookieprofile',
            name='have_read',
            field=models.ManyToManyField(blank=True, default=None, related_name='have_read', to='book.book'),
        ),
        migrations.AddField(
            model_name='bookieprofile',
            name='want_to_read',
            field=models.ManyToManyField(blank=True, default=None, related_name='want_to_read', to='book.book'),
        ),
    ]
