# Generated by Django 5.0.2 on 2024-03-20 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookieProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(default='static/images/profile_pictures/no_profile_pic.png', upload_to='static/images/profile_pictures/')),
                ('bio', models.TextField(blank=True, default='Tell something about yourself in 250 characters or less.', max_length=250)),
            ],
        ),
    ]
