# Generated by Django 5.0.2 on 2024-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0002_bookieprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookie',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Another bookie is already using that email.'}, max_length=100, null=True),
        ),
    ]
