# Generated by Django 5.0.2 on 2024-04-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0002_bookie_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookieprofile',
            old_name='bookie',
            new_name='user',
        ),
    ]
