# Generated by Django 5.0.2 on 2024-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_cover_image'),
        ('bookie', '0003_alter_bookie_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookieprofile',
            name='books_i_want_to_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='books_wanted_by_users', to='book.book'),
        ),
        migrations.AddField(
            model_name='bookieprofile',
            name='books_ive_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='books_read_by_users', to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookieprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/no_profile_pic.png', null=True, upload_to='static/images'),
        ),
    ]
