# Generated by Django 5.0.2 on 2024-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bookie', '0003_rename_bookie_bookieprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookieprofile',
            options={'default_related_name': 'profile'},
        ),
        migrations.AddField(
            model_name='bookie',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='bookie',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
