# Generated by Django 5.0.2 on 2024-04-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0004_alter_bookieprofile_options_bookie_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
