# Generated by Django 5.0.2 on 2024-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0005_alter_bookieprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Share something about yourself.', null=True),
        ),
    ]
