# Generated by Django 5.0.2 on 2024-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_cover_image'),
        ('bookie', '0005_alter_bookieprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='books_i_want_to_read',
            field=models.ManyToManyField(blank=True, related_name='books_wanted_by_users', to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookieprofile',
            name='books_ive_read',
            field=models.ManyToManyField(blank=True, related_name='books_read_by_users', to='book.book'),
        ),
    ]
