# Generated by Django 5.0.2 on 2024-04-02 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0006_alter_bookieprofile_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookieprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='bookieprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
