# Generated by Django 5.0.2 on 2024-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0006_alter_bookieprofile_books_i_want_to_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/no_profile_pic.jpg', null=True, upload_to='static/images/'),
        ),
    ]
