# Generated by Django 5.0.2 on 2024-03-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_cover_image'),
        ('bookie', '0007_alter_bookieprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='bio',
            field=models.TextField(blank=True, default='Share something about yourself in 250 characters or less.', max_length=250),
        ),
        migrations.AlterField(
            model_name='bookieprofile',
            name='books_i_want_to_read',
            field=models.ManyToManyField(blank=True, default='No books added yet', related_name='books_wanted_by_users', to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookieprofile',
            name='books_ive_read',
            field=models.ManyToManyField(blank=True, default='No books read yet', related_name='books_read_by_users', to='book.book'),
        ),
    ]
