# Generated by Django 5.0.2 on 2024-03-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0008_alter_bookieprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookieprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
