# Generated by Django 5.0.2 on 2024-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0009_bookieprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='profile_picture',
            field=models.ImageField(default='images/no_profile_pic.jpg', upload_to='image/'),
        ),
    ]
