# Generated by Django 5.0.2 on 2024-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0010_bookieprofile_date_joined_alter_bookie_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookieprofile',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='bookie',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
