# Generated by Django 5.0.2 on 2024-03-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0010_alter_bookieprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://www.pngitem.com/pimgs/m/22-223978_transparent-no-avatar-png-pyrenees-png-download.png'),
        ),
    ]
