# Generated by Django 5.0.2 on 2024-03-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('category', '0002_category_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='books_in_category', to='book.book'),
        ),
    ]
