# Generated by Django 5.0.2 on 2024-03-27 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Author with this name already exists.'}, max_length=100, unique=True, verbose_name='Author name')),
                ('year_born', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)], verbose_name='Author`s birth year')),
                ('author_picture', models.ImageField(default='images/no_profile_pic.jpg', upload_to='images/')),
                ('authors_bio', models.TextField(help_text='A brief description of the author. Use at least 40 characters.', max_length=1000, validators=[django.core.validators.MinLengthValidator(40)])),
            ],
        ),
    ]
