# Generated by Django 5.0.2 on 2024-03-21 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_born',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)], verbose_name='Author`s birth year'),
        ),
    ]
