# Generated by Django 5.0.2 on 2024-04-05 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_pseudonym_alter_author_author_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authors_bio',
            field=models.TextField(help_text='Use at least 40 characters.', max_length=1000, validators=[django.core.validators.MinLengthValidator(40)]),
        ),
    ]
