# Generated by Django 5.0.2 on 2024-04-05 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_authors_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='year_born',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)], verbose_name='Author`s birth year'),
        ),
    ]
