# Generated by Django 5.0.2 on 2024-04-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_author_year_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_picture',
            field=models.ImageField(default='no_profile_pic.jpg', upload_to='authors_pictures'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Author name'),
        ),
    ]
