# Generated by Django 5.0.2 on 2024-04-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_alter_author_author_picture_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_picture',
            field=models.ImageField(default='no_profile.png', upload_to='authors_pictures'),
        ),
    ]
