# Generated by Django 5.0.2 on 2024-04-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_author_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.CharField(default='Unknown'),
        ),
    ]
