# Generated by Django 5.0.2 on 2024-04-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_alter_author_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(default='Unknown', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='author.country'),
        ),
    ]
