# Generated by Django 5.0.2 on 2024-04-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_alter_country_options_alter_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
