# Generated by Django 5.0.2 on 2024-03-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewandrating',
            old_name='current_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reviewandrating',
            name='ip',
        ),
    ]
