# Generated by Django 5.0.2 on 2024-03-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('reviews', '0002_rename_current_user_reviewandrating_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewandrating',
            name='status',
        ),
        migrations.AddField(
            model_name='reviewandrating',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='book.book'),
        ),
    ]
