# Generated by Django 5.0.2 on 2024-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewandrating_book_reviewandrating_has_voted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='type',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Neutral', max_length=10),
        ),
    ]
