# Generated by Django 5.0.2 on 2024-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviewandrating_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewandrating',
            name='type',
            field=models.CharField(choices=[('positive', 'positive'), ('negative', 'negative'), ('neutral', 'neutral')], default='Neutral', max_length=10),
        ),
    ]
