# Generated by Django 5.0.2 on 2024-04-04 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_reviewandrating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandrating',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
