# Generated by Django 5.0.2 on 2024-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviewandrating_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
