# Generated by Django 5.0.2 on 2024-04-02 11:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genre', '0002_genre_delete_category'),
        ('author', '0002_author_author_picture_author_authors_bio_author_name_and_more'),
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(help_text='If you can`t find the Genre you need,\nplease contact the administrator at denny@gmail.com.', null=True, to='Genre.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='no_cover.jpg', upload_to='cover_images'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Describe the book in at least 100 characters.', max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(default=2024, help_text='If the book you are trying to add was published before 1000,\nplease contact the administrator at denny@gmail.com.', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
