# Generated by Django 5.0.2 on 2024-04-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/book_cover_no_img.jpg', upload_to='images/'),
        ),
    ]
