# Generated by Django 5.0.2 on 2024-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/book_cover_no_img.jpg', upload_to='static/images/'),
        ),
    ]
