# Generated by Django 5.0.2 on 2024-04-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genre', '0002_genre_delete_category'),
        ('book', '0002_book_added_by_book_author_book_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(help_text='If you can`t find the Genre you need,\nplease contact the administrator at denny@gmail.com.', to='Genre.genre'),
        ),
    ]
