# Generated by Django 5.0.2 on 2024-03-20 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_author_alter_book_title'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(default='Not set yet', to='category.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='static/images/book_pics/no_cover.png', upload_to='static/images/book_pics/'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Describe the book in at least 100 characters.', max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
