# Generated by Django 5.0.2 on 2024-04-01 10:33

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='images/book_cover_no_img.jpg', upload_to=book.models.custom_upload_to),
        ),
    ]
