# Generated by Django 5.0.2 on 2024-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='static/images/no_cover.png', upload_to='static/images'),
        ),
    ]
