# Generated by Django 5.0.2 on 2024-04-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='book/cover_images/book_cover_no_img.jpg', upload_to='book/cover_images'),
        ),
    ]
