# Generated by Django 5.0.2 on 2024-04-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='no_cover.jpg', null=True, upload_to='static/images'),
        ),
    ]
