# Generated by Django 5.0.2 on 2024-04-06 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0012_alter_country_options_alter_author_country'),
        ('book', '0006_alter_book_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='author.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Describe the book in at least 100 characters.', max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(100), django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.CreateModel(
            name='BookRequestFromUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('year_published', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)])),
                ('is_anonymous', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
