# Generated by Django 5.0.2 on 2024-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='static/images/book_cover_no_img.jpg', upload_to='static/images/'),
        ),
    ]
