# Generated by Django 5.0.2 on 2024-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='images/book_cover_no_img.jpg', upload_to='images/'),
        ),
    ]
