# Generated by Django 5.0.2 on 2024-04-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequestfromusermodel',
            name='is_anonymous',
        ),
    ]
