# Generated by Django 5.0.2 on 2024-03-25 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_cover_image'),
        ('category', '0002_category_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(help_text='If you can`t find the category you need,\nplease contact the administrator at denny@gmail.com.', to='category.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.PositiveIntegerField(default=2024, help_text='If the book you are trying to add was published before 1000,\nplease contact the administrator at denny@gmail.com.', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
