# Generated by Django 5.0.2 on 2024-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_las_edited_on_date_book_last_edited_on_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
