# Generated by Django 5.0.2 on 2024-04-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
