# Generated by Django 5.0.2 on 2024-04-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='last_edited_by_email',
        ),
    ]
