# Generated by Django 5.0.2 on 2024-04-02 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genre', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('age_restriction', models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(50)])),
                ('books', models.ManyToManyField(blank=True, related_name='books_in_category', to='book.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
