# Generated by Django 5.0.2 on 2024-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genre', '0002_genre_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_image',
            field=models.ImageField(default='no_cover.jpg', upload_to='genre_images'),
        ),
    ]
